runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: gunicorn --bind :$PORT app:app

instance_class: F2

env_variables:
  BUCKET_NAME: "personal-fa-starter-app.appspot.com"

handlers:
  - url: /
    static_files: dist/client/index.html
    upload: dist/client/index.html

  - url: /.*
    static_files: dist/client/index.html
    upload: dist/client/index.html
