runtime: python39

entrypoint: gunicorn --bind :$PORT app:app

instance_class: F2

env_variables:
  BUCKET_NAME: "personal-fa-starter-app.appspot.com"


vpc_access_connector:
  name: projects/personal-fa-starter-app/locations/us-west2/connectors/obabel-connector
  egress_setting: all-traffic

handlers:
  - url: /.*
    script: auto
