runtime: python39

entrypoint: gunicorn --bind :$PORT personal-fa-starter-app.wl.r.appstop.com:app

instance_class: F2

env_variables:
  BUCKET_NAME: "personal-fa-starter-app.appspot.com"

handlers:
  - url: /.*
    script: auto
