runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: gunicorn --bind :$PORT app:app

instance_class: F2

env_variables:
  BUCKET_NAME: "personal-fa-starter-app.appspot.com"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
